### ISSUE TITLE
new version with "subraid" compilation error. 

### ISSUE THREAD

**Issue by Tortoise17** [JohnWStockwellJr/SeisUnix#108]
Dear Respected Sir, 

Here is little problem with new function installation. 
```

/bin/subraid
subraid.c: In function ‘compdouble’:
subraid.c:234:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  234 |   for(int n=0; n<nkeys; n++) {
      |   ^~~
subraid.c:234:3: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
```

I tried to check but the flags are there and it is still throwing compilation error. If you have any guess.

**Comment by JohnWStockwellJr** [comment]
Install 44R23 instead
You will need to change all occurrences of 
18 to 23
In $CWPROOT/src/Makefile
in 44R23

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by JohnWStockwellJr** [comment]
Thanks to Andre Latour, the problem is fixed. I have uploaded a new tar file:   incremental release 44R25  at https://wiki.Seismic-Unix.org 




John Stockwell   | ***@***.***

https://wiki.Seismic-Unix.org 
(The New Home of Seismic Un*x)
