### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by thelvaci** [JohnWStockwellJr/SeisUnix#12]
make[4]: Entering directory '/opt/SU/src/su/main/amplitudes'
gcc -I/opt/SU/include -g  -std=c99 -Wall -pedantic -Wno-long-long  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DCWP_LITTLE_ENDIAN -DSUXDR  -D_DEFAULT_SOURCE -D_POSIX_SOURCE sucentsamp.c  -L/opt/SU/lib -lsu -lpar -lcwp -lm  -o /opt/SU/bin/sucentsamp
/opt/SU/lib/libsu.a(fgettr.o): In function `dataread':
/opt/SU/src/su/lib/fgettr.c:148: undefined reference to `xdr_float'
/opt/SU/src/su/lib/fgettr.c:148: undefined reference to `xdr_vector'
/opt/SU/lib/libsu.a(fgettr.o): In function `fgettr_internal':
/opt/SU/src/su/lib/fgettr.c:203: undefined reference to `xdrmem_create'
/opt/SU/lib/libsu.a(fputtr.o): In function `datawrite':
/opt/SU/src/su/lib/fputtr.c:123: undefined reference to `xdr_float'
/opt/SU/src/su/lib/fputtr.c:123: undefined reference to `xdr_vector'
/opt/SU/lib/libsu.a(fputtr.o): In function `fputtr_internal':
/opt/SU/src/su/lib/fputtr.c:171: undefined reference to `xdrmem_create'
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
/opt/SU/src/su/lib/xdrhdrsub.c:42: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:43: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:44: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:45: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:46: undefined reference to `xdr_int'
/opt/SU/lib/libsu.a(xdrhdrsub.o):/opt/SU/src/su/lib/xdrhdrsub.c:47: more undefined references to `xdr_int' follow
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
/opt/SU/src/su/lib/xdrhdrsub.c:51: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:53: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:58: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:60: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:63: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:64: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:65: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:66: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:67: undefined reference to `xdr_int'
/opt/SU/lib/libsu.a(xdrhdrsub.o):/opt/SU/src/su/lib/xdrhdrsub.c:68: more undefined references to `xdr_int' follow
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
/opt/SU/src/su/lib/xdrhdrsub.c:73: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:75: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:78: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:79: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:80: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:81: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:84: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:86: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:91: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:93: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:98: undefined reference to `xdr_u_int'
/opt/SU/lib/libsu.a(xdrhdrsub.o):/opt/SU/src/su/lib/xdrhdrsub.c:100: more undefined references to `xdr_u_int' follow
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
/opt/SU/src/su/lib/xdrhdrsub.c:243: undefined reference to `xdr_float'
/opt/SU/src/su/lib/xdrhdrsub.c:244: undefined reference to `xdr_float'
/opt/SU/src/su/lib/xdrhdrsub.c:245: undefined reference to `xdr_float'
/opt/SU/src/su/lib/xdrhdrsub.c:246: undefined reference to `xdr_float'
/opt/SU/src/su/lib/xdrhdrsub.c:247: undefined reference to `xdr_float'
/opt/SU/lib/libsu.a(xdrhdrsub.o):/opt/SU/src/su/lib/xdrhdrsub.c:248: more undefined references to `xdr_float' follow
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
/opt/SU/src/su/lib/xdrhdrsub.c:249: undefined reference to `xdr_int'
/opt/SU/src/su/lib/xdrhdrsub.c:252: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:254: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:259: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:261: undefined reference to `xdr_u_int'
/opt/SU/src/su/lib/xdrhdrsub.c:263: undefined reference to `xdr_u_int'
/opt/SU/lib/libsu.a(xdrhdrsub.o):/opt/SU/src/su/lib/xdrhdrsub.c:265: more undefined references to `xdr_u_int' follow
collect2: error: ld returned 1 exit status
make[4]: [Makefile:31: /opt/SU/bin/sucentsamp] Error 1 (ignored)
chmod: cannot access '/opt/SU/bin/sucentsamp': No such file or directory
make[4]: *** [Makefile:32: /opt/SU/bin/sucentsamp] Error 1
make[4]: Leaving directory '/opt/SU/src/su/main/amplitudes'
make[3]: *** [Makefile:37: remake] Error 2
make[3]: Leaving directory '/opt/SU/src/su/main/amplitudes'
make[2]: *** [Makefile:34: remake] Error 2
make[2]: Leaving directory '/opt/SU/src/su/main'
make[1]: *** [Makefile:15: remake] Error 2
make[1]: Leaving directory '/opt/SU/src/su'
make: *** [Makefile:137: remake] Error 2

**Comment by JohnWStockwellJr** [comment]
Hi,
What operating system are you installing under. What Makefile.config are you using?

**Comment by thelvaci** [comment]
Hi John,
Fedora 28, Linux. -xc99 in Makefle.config 
I think I have spotted the reason: glibc does not contain rpc libraries anymore in Fedora 28. libtipc and libtipc-devel package must be installed. How to modify the Makefile and or Makefile.config files?
Regards,

**Comment by JohnWStockwellJr** [comment]
So, install  libtipc and libtipc-devel

**Comment by thelvaci** [comment]
Hi John,

They are libtirpc and libtirpc-devel. I have installed them corrected the source code for /usr/include/tirpc/rpc. Still i get the same error 
make[3]: Entering directory '/opt/SU/src/su/main/amplitudes'
gcc -I/opt/SU/include -O  -std=c99 -Wall -pedantic -Wno-long-long  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DCWP_LITTLE_ENDIAN -DSUXDR  -D_DEFAULT_SOURCE -D_POSIX_SOURCE sucentsamp.c  -L/opt/SU/lib -lsu -lpar -lcwp -lm  -o /opt/SU/bin/sucentsamp
/opt/SU/lib/libsu.a(fgettr.o): In function `dataread':
fgettr.c:(.text+0x158): undefined reference to `xdr_float'
fgettr.c:(.text+0x164): undefined reference to `xdr_vector'
/opt/SU/lib/libsu.a(fgettr.o): In function `fgettr_internal':
fgettr.c:(.text+0x2b0): undefined reference to `xdrmem_create'
/opt/SU/lib/libsu.a(fputtr.o): In function `fputtr_internal':
fputtr.c:(.text+0x111): undefined reference to `xdr_float'
fputtr.c:(.text+0x11b): undefined reference to `xdr_vector'
fputtr.c:(.text+0x324): undefined reference to `xdrmem_create'
/opt/SU/lib/libsu.a(xdrhdrsub.o): In function `xdrhdrsub':
xdrhdrsub.c:(.text+0x16): undefined reference to `xdr_int'
 more undefined references to `xdr_int' follow
and lots of same kind of error messages.
It can not find the xdr_float, xdr_int etc., functions and the library containing it. 
What is the library of xdr routines?
Regards,

**Comment by JohnWStockwellJr** [comment]
What do you mean “corrected the source code”?

**Comment by JohnWStockwellJr** [comment]
xdr is intrinsic to all Unix and Unix-like systems.

**Comment by thelvaci** [comment]
Hi John,
Sorry my mistake. I edited the /usr/include/tirpc/rpc/xdr.h to include
tirpc instead of rpc.
However I've undone to keep it as it is and create a link in /usr/include
folder showing rpc->tirpc
When I run make install I get
.
.
.
/opt/SU/lib/libsu.a(fgettr.o): In function `dataread':
fgettr.c:(.text+0x158): undefined reference to `xdr_float'
fgettr.c:(.text+0x164): undefined reference to `xdr_vector'
/opt/SU/lib/libsu.a(fgettr.o): In function `fgettr_internal':
.
.
Does this show that it can not find the xdr library or is it something else?
What to edit for the  good compilation?
Best Regards,
Tahir

**Comment by thelvaci** [comment]
A better explanation:
I 've downloaded SU44R12 from  Git. When I try to make install I get after entering amplitudes folder I get the following error messages and make aborts.
OS is Fedora 28 gcc is c version 8.1.1 20180712 (Red Hat 8.1.1-5) (GCC)
My makefile.config file is for GNU compiler and the switch is -std=c99.
I don't know where to look for sorting this out.
Best Regards,
Tahir
make[4]: Entering directory '/opt/SU/src/su/main/amplitudes'
gcc -I/opt/SU/include -O  -std=c99 -Wall -pedantic -Wno-long-long  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DCWP_LITTLE_ENDIAN -DSUXDR  -D_DEFAULT_SOURCE -D_POSIX_SOURCE sucentsamp.c  -L/opt/SU/lib -lsu -lpar -lcwp -lm  -o /opt/SU/bin/sucentsamp
/opt/SU/lib/libsu.a(fgettr.o): In function `dataread':
fgettr.c:(.text+0x158): undefined reference to `xdr_float'
fgettr.c:(.text+0x164): undefined reference to `xdr_vector'
/opt/SU/lib/libsu.a(fgettr.o): In function `fgettr_internal':

**Comment by thelvaci** [comment]
Sorted out:
Add -ltirpc deliberately.

**Comment by JohnWStockwellJr** [comment]
You shouldn’t have to do any of this. You definitely should not be changing system level include files. Ever.

You should be able to use “git” to download SU from 

https://github.com/JohnWStockwellJr/SeisUnix

Set the CWPROOT path
Then do
make remake
make xtremake

On any Linux system this should be straightforward.

**Comment by JohnWStockwellJr** [comment]
You should use the default Makefile.config

**Comment by JohnWStockwellJr** [comment]
Ok. Good to know.

**Comment by balaperumal97** [comment]
how to install the make finstall, make mglinstall, make xminstall, make sinstall. then it have some error.how can in install this file? this is a first error.
collect2: error: ld returned 1 exit status
Makefile:16: recipe for target '/home/bala/SeisUnix-master/bin/vpluszf' failed
make[2]: *** [/home/bala/SeisUnix-master/bin/vpluszf] Error 1
make[2]: Leaving directory '/home/bala/SeisUnix-master/src/Fortran/Vplusz'
Makefile:6: recipe for target 'INSTALL' failed
make[1]: *** [INSTALL] Error 2
make[1]: Leaving directory '/home/bala/SeisUnix-master/src/Fortran'
Makefile:126: recipe for target 'finstall' failed
make: *** [finstall] Error 2
2. second error
trip.c:10:10: fatal error: GL/glu.h: No such file or directory
 #include "GL/glu.h"
          ^~~~~~~~~~
compilation terminated.
Makefile:21: recipe for target '/home/bala/SeisUnix-master/bin/trip' failed
make[2]: *** [/home/bala/SeisUnix-master/bin/trip] Error 1
make[2]: Leaving directory '/home/bala/SeisUnix-master/src/Mesa/main'
Makefile:6: recipe for target 'INSTALL' failed
make[1]: *** [INSTALL] Error 2
make[1]: Leaving directory '/home/bala/SeisUnix-master/src/Mesa'
Makefile:123: recipe for target 'mglstuff' failed
make: *** [mglstuff] Error 2
3.third error.
/home/bala/SeisUnix-master/include/Xmcwp/Xmcwp.h:8:10: fatal error: Xm/Xm.h: No such file or directory
 #include <Xm/Xm.h>
          ^~~~~~~~~
compilation terminated.
/home/bala/SeisUnix-master/src/Rules/suffix.rules:4: recipe for target '/home/bala/SeisUnix-master/lib/libXmcwp.a(radiobuttons.o)' failed
make[2]: *** [/home/bala/SeisUnix-master/lib/libXmcwp.a(radiobuttons.o)] Error 1
make[2]: Leaving directory '/home/bala/SeisUnix-master/src/Xmcwp/lib'
Makefile:6: recipe for target 'INSTALL' failed
make[1]: *** [INSTALL] Error 2
make[1]: Leaving directory '/home/bala/SeisUnix-master/src/Xmcwp'
Makefile:100: recipe for target 'xmcwp_' failed
make: *** [xmcwp_] Error 2
4.fourth error.
compilation terminated.
/home/bala/SeisUnix-master/src/Rules/suffix.rules:4: recipe for target '/home/bala/SeisUnix-master/lib/libXmcwp.a(radiobuttons.o)' failed
make[2]: *** [/home/bala/SeisUnix-master/lib/libXmcwp.a(radiobuttons.o)] Error 1
make[2]: Leaving directory '/home/bala/SeisUnix-master/src/Xmcwp/lib'
Makefile:6: recipe for target 'INSTALL' failed
make[1]: *** [INSTALL] Error 2
make[1]: Leaving directory '/home/bala/SeisUnix-master/src/Xmcwp'
Makefile:100: recipe for target 'xmcwp_' failed
make: *** [xmcwp_] Error 2
bala@bala-Lenovo-E41-15:~/SeisUnix-master/src$ make sinstall
make: *** No rule to make target 'sinstall'.  Stop.
bala@bala-Lenovo-E41-15:~/SeisUnix-master/src$ make sinstall
make: *** No rule to make target 'sinstall'.  Stop.
sir please tell me the answer sir.
