### ISSUE TITLE
suximage: fgettr.c: bad first header

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#139]
I keep getting the error "suximage: fgettr.c: bad first header" when i try to use suximage, supswigb from a shell script, BUT they both plot out the figure when I use the command line

My code below:
suximage <$SFILTGATHERS/sugc_DipFilt_$fldr.su label1="Traveltime [s]" label2="offset [m]" title="DIP_Filtered data_$fldr" &

PS: suximage has always worked for me inn the past.

**Comment by JohnWStockwellJr** [comment]
Can you send me your shell script?

**Comment by doziej84** [comment]
Hello John...I was ble able to rectify it. I had an Ampersand in a line of code before it.
Thanks.

Pls I do have another issue with sudipfilt. The wavenumber axis of my suspecfx plots don't look realistic.

**Comment by JohnWStockwellJr** [comment]
You can communicate with me directly at:        j o h n . 1 9  0 7 1 9 6 9 @ g m a I l . c o m


John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
