### ISSUE TITLE
edit Makefile.config

### ISSUE THREAD

**Issue by LeeyMessi** [JohnWStockwellJr/SeisUnix#14]
hello, Mr, I am reading that "Installation_Instructions", and I have understand step 1,2,3,4,5,6. But I am lost when meeting to step 7. I don't know how to edit Makefile.config.  Could you give me a demo? My server's system is RedHat 7.4 ..thank you!

**Comment by JohnWStockwellJr** [comment]
You should just be able to use the default Makefile.config

**Comment by LeeyMessi** [comment]
thank you very much ! I have tried Step 7: sub-step 2, Unfortunately, I meet that `In file included from Axes.c:72:0:
/home/seismic/su/include/Xtcwp/Xtcwp.h:18:27: fatal error: X11/Intrinsic.h: No such file or directory
 #include <X11/Intrinsic.h>
                           ^
compilation terminated.
make[3]: *** [/home/seismic/su/lib/libXtcwp.a(Axes.o)] Error 1
make[3]: Leaving directory `/home/seismic/su/src/Xtcwp/lib'
make[2]: *** [remake] Error 2
make[2]: Leaving directory `/home/seismic/su/src/Xtcwp/lib'
make[1]: *** [remake] Error 2
make[1]: Leaving directory `/home/seismic/su/src/Xtcwp'
make: *** [xtremake] Error 2
` after running `make xtinstall`

**Comment by o1e9** [comment]
On 06. sep. 2018 15:11, LeeyMessi wrote:
> thank you very much ! I have tried Step 7: sub-step 2, Unfortunately, I 
> meet that |In file included from Axes.c:72:0: 
> /home/seismic/su/include/Xtcwp/Xtcwp.h:18:27: fatal error: 
> X11/Intrinsic.h: No such file or directory #include <X11/Intrinsic.h> ^ 
> compilation terminated. make[3]: *** 
> [/home/seismic/su/lib/libXtcwp.a(Axes.o)] Error 1 make[3]: Leaving 
> directory|/home/seismic/su/src/Xtcwp/lib'
> make[2]: *** [remake] Error 2
> make[2]: Leaving directory |/home/seismic/su/src/Xtcwp/lib' make[1]: *** 
> [remake] Error 2 make[1]: Leaving directory|/home/seismic/su/src/Xtcwp'
> make: *** [xtremake] Error 2
> |after running|make xtinstall`
> 

You would need to install additional _-devel_ packages.

First locate the desired package with the following command:

yum provides \*X11/Intrinsic.h

Then install it with "yum install _package name_"

You may use _yum provides_ for other issue if .h or .so files are 
missing on your system.

**Comment by LeeyMessi** [comment]
thank your help! I had typed  `yum provides \*X11/Intrinsic.h`,then run `yum install libXt-devel-1.1.5-3.el7.x86_64`,yeah, that's successful! those operating was executed as root. But I typed `make xtinstall`as not root ,and the previous problem still appears, @o1e9

**Comment by LeeyMessi** [comment]
thank you !  Sr, I am a college student that major in geophysical, because I am  a stupid student, Or I don't know much about computers,  could you tell me in detail how to do it? @JohnWStockwellJr

**Comment by o1e9** [comment]
On 08. sep. 2018 07:51, LeeyMessi wrote:
> thank your help! I had typed |yum provides \*X11/Intrinsic.h|,then run 
> |yum install libXt-devel-1.1.5-3.el7.x86_64|,yeah, that's successful! 
> those operating was executed as root. But I typed |make xtinstall|as not 
> root ,and the previous problem still appears, @o1e9 

You are using x86_64 system, besides /usr/X11* is no longer available in 
Filesystem Hierarchy Standard (FHS) and as a consequences in modern 
RHEL/CentOS/Ubuntu systems.  Try to replace the following variables in 
Makefile.config:

IX11 = /usr/include
LX11 = /usr/lib64
IMOTIF = /usr/include
LMOTIF = /usr/lib64

You would have to install some GLU and XMotif development packages as 
well.  Use _yum provides_ and following _yum install_ the same way as 
for Xt.

**Comment by JohnWStockwellJr** [comment]
There is more than just libXt.a there are several libX... items that you need to install.

**Comment by LeeyMessi** [comment]
thank you! Sr,, I did as you said. @JohnWStockwellJr

**Comment by JohnWStockwellJr** [comment]
Have you restarted your computer after installing the X windows code?

**Comment by LeeyMessi** [comment]
Yes，I have restarted my machine, but terminal shows `xwigb: Cannot connect to display` after `running suplane | suxwigb &`

**Comment by JohnWStockwellJr** [comment]
Try typing:

xhost +

And then
suplane | suxwigb &

**Comment by JohnWStockwellJr** [comment]
Explain to me what computer system, and operating system you are using?

**Comment by LeeyMessi** [comment]
`xhost:  unable to open display ""` after running `xhost + `,,my machine is the server of dell ,which model id R730, and my operating system is RedHat 7.4,,, @JohnWStockwellJr

**Comment by JohnWStockwellJr** [comment]
Are you logged in as a regular user or as root?

**Comment by LeeyMessi** [comment]
as a regular when `make install /xtinstall ...` and ran `xhost + /suplane | suxwigb & `

**Comment by JohnWStockwellJr** [comment]
What computer type and operating system are you running?

**Comment by o1e9** [comment]
On 09. sep. 2018 06:30, LeeyMessi wrote:
> |xhost: unable to open display ""| after running |xhost +|,,my machine 
> is the server of dell ,which model id R730, and my operating system is 
> RedHat 7.4,,, @JohnWStockwellJr <https://github.com/JohnWStockwellJr>

I assume you are connecting remotely to that server.  Do you use SSH? 
In case of SSH you would have to update your /etc/ssh/sshd_config on 
server and set _X11Forwarding yes_ then restart SSHD service:

systemctl restart sshd

Try to connect from your desktop using -X option in ssh client:

ssh -X username@yourservername

If you are running client on Linux then make custom configuration for 
your server.  Update file ~/.ssh/config and add following:

Host yourservername_is_here
     ForwardX11 yes
     ForwardX11Trusted yes

If you are running client on Windows, the alternative would be to deploy 
one of the lightweight desktop environments (Mate or Xfce) and use xrdp 
or x2go service to access remote server as desktop.

**Comment by LeeyMessi** [comment]
Thank you sincerely! I have solved all problems with your help,, Thank you! I am successful! @o1e9

**Comment by JohnWStockwellJr** [comment]
Very good.
