### ISSUE TITLE
Velan.radon

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#145]
I am using the velan.radon script for velocity analysis....Pls what would make someone obtain a semblance panel like this? and what can I do to adjust it to be able to distinctly see the bulls eye and pick the stacking velocities? Has anyone encountered this while doing velocity analysis
![Screen Shot 2023-03-17 at 8 39 23 PM](https://user-images.githubusercontent.com/5464363/226076934-6a26e9b9-37ae-4b1e-b961-116d75d306b1.png)

**Comment by JohnWStockwellJr** [comment]
Is your input data sorted in cdps? What is the fold of the data? It looks like you don’t have enough traces.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by JohnWStockwellJr** [comment]
Your velocity spectrum is starting at 500m/s and goes to 2000 m/s. That seems to be a bit low.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by JohnWStockwellJr** [comment]
Please email me directly at     j o h n . 1 9 0 7 1 9 6 9 @ g m a i l . c o m

So we can continue this discussion. Also, when sending a text file, please give it a name ending in .txt

**Comment by doziej84** [comment]
I just sent you an email
