### ISSUE TITLE
error using SURESSTAT  "62794 Segmentation fault: 11"

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#146]
I get an error using SURESSTAT  "62794 Segmentation fault: 11"

Does anyone know what could be the issue?

below is my code
suresstat <fldrsort_data15.su ssol=sstats15 rsol=rstats15 ntraces=2256 ntpick=50 niter=5 nshot=47 nr=48 nc=234 sfold=47 rfold=47 cfold=47

**Comment by l2r-git** [comment]
I do not know anything about the suresstat program, but, generally, a "segmentation fault" means the program has attempted to use memory that has not been given to it.

I looked at suresstat code and the ntraces parameter must be the EXACT number of input traces.

Everything else just needs to be BIGGER. 
So try setting nshot,nr,nc,sfold,rfold,cfold BIGGER.

And, I have read the suresstat code, and this is what I think the parameters actually mean: 

  nshot=the maximum fldr value in your traces (not actually the max amount of shots)
  nr=the maximum tracf value in your traces (not actually the max amount of receivers)
  nc=the maximum cdp value in your traces (not actually the max amount of cdps)

  sfold=maximum amount of traces that have the same fldr value 
  rfold=maximum amount of traces that have the same tracf value
  cfold=maximum amount of traces that have the same cdp value

Also, try setting parameter verbose=1. This may give more details about the problem.

**Comment by doziej84** [comment]
Thank you
