### ISSUE TITLE
Sustolt error

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#147]
I get an error "sustolt: cannot handle non-zero time of first sample although my starting time is 0.0. What could be wrong?

sustolt cdpmin=1 cdpmax=234 dxcdp=5 <indata.su >outdata.su verbose=1 tmig=0.0,0.000967219,0.165172,0.287713,0.42741,0.500934,0.790131,0.90777,1.09893,1.3048,1.35812,1.64305,1.89913,1.99651,2.63491,2.79361 vmig=421.42,425.959,500.128,509.399,550.192,581.714,613.235,635.486,657.737,733.76,922.33,1085.45,1233.75,1312.84,1451.25,1510.57

**Comment by JohnWStockwellJr** [comment]
Does your data start at 0.0? You can tell if surange shows that the delrt parameter is something nonzero. You may need to correct your data using “sushift”  to remove the shift

Please communicate with me directly at:    j o h n . 1 9 0 7 1 9 6 9 @ g m a i l . c o m

**Comment by doziej84** [comment]
Thank you. That worked for me
