### ISSUE TITLE
Dip moveout error (DMO)

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#149]
I got several of the following errors while implementing DMO. Can anyone give me an idea on what I could do to solve this problem?

 sudmofk: ealloc.c: malloc failed (Cannot allocate memory)
sudmofk(3544,0x11511cdc0) malloc: can't allocate region
:*** mach_vm_map(size=18446744065119621120, flags: 100) failed (error code=3)
sudmofk(3544,0x11511cdc0) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by JohnWStockwellJr** [comment]
Hi,
Please email me directly 
at: j o h n . 1 9 0 7 1 9 6 9 @ g m a i l . c o m

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
