### ISSUE TITLE
sumiggbzo: error reading vfile=unewvelzx.bin!

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#151]
I am trying to perform Gaussian Beam migration. I keep getting the error "sumiggbzo: error reading vfile=unewvelzx.bin!"

The unewvelzx.bin file is present.

what could be the problem?

**Comment by JohnWStockwellJr** [comment]
That velocity file has to have the same dimensions as your input stacked section.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by doziej84** [comment]
Hi, 
What Dimensions are you referring to?
    On Sunday, April 9, 2023 at 08:04:25 AM CDT, John Stockwell ***@***.***> wrote:  
 
 

That velocity file has to have the same dimensions as your input stacked section.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by JohnWStockwellJr** [comment]
The velocity file has to have the same number of values as the stacked section you are migrating.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
