### ISSUE TITLE
Missing CDP's

### ISSUE THREAD

**Issue by doziej84** [JohnWStockwellJr/SeisUnix#153]
I am supposed to have 234 cdp's but I can only count 94. Also, the cdp's don't increase sequentially. 

Can anyone take a look at the attached picture and maybe give me an idea of what is wrong here? ![missing cdp](https://user-images.githubusercontent.com/5464363/233225400-375e02ee-b412-4f1f-af63-8093f2ffd68a.png)

**Comment by l2r-git** [comment]
First, to clarify: surange saying cdp 1 234 (1 - 234) does not mean that that it found all cdp numbers between 1 and 234.
Surange just means the minimum was 1 and the maximum was 234.

If you used sucdpbin to compute the cdp numbers then you may have set the dcdp parameter wrong.
Try dividing your dcdp value by 2. If that does not help, try multiplying your dcdp by 2. 

Typically, dcdp is half the distance between receivers, or half the distance between shots, whichever is smaller.
But when distance-between-shots and distance-between-receivers is not a simple whole number ratio, things get complicated.

**Comment by doziej84** [comment]
I did not use sucdpbin to compute cdp numbers. I only used the suchw to set the offset and cdp. My source and receiver spacing is both 5m, with the source at the receiver locations.

**Comment by l2r-git** [comment]
OK.
 
Unfortunately, all header keys in Seismic Unix are integers. 
Therefore, if you divide 5m by 2 you get 2.5 which will truncate if you put it into a key.
So will values like 15 or 25 and so on.
(You can see that the offset range output by surange is -232 233 which should not be possible with spacings of 5 and shots at the receiver locations).

Note that Seismic Unix handles this problem using the scalco key. 
This allows you scale the coordinates.

Probably the easiest thing to do is to set shot and receiver sx and gx values to spacings of 50.

If you do use 50, then also use suchw to set scalco=-10   This will tell other programs to divide sx,sy,gx,gy by 10 before use.
I just looked into the suchw program code and it ignores scalco so you can set it to -10 anytime.
But that also means you have to check your offset computation.

**Comment by l2r-git** [comment]
Additional...Yes, scalco should be set to **negative** 10 if you use 50 spacings.

**Comment by doziej84** [comment]
how do I set scalco to -10? is it setting d=-10 using suchw?

**Comment by JohnWStockwellJr** [comment]
Try sushw key=scalco a=-10 < infile.su >outfile.su

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
