### ISSUE TITLE
 synthetic data with multiples

### ISSUE THREAD

**Issue by LeeyMessi** [JohnWStockwellJr/SeisUnix#19]
hello, Sir! I meet a problem that I need to make synthetic data with multiples, please, Could SU do this task? If it can, how to do it? Thank you ！

**Comment by JohnWStockwellJr** [comment]
It depends on what you are doing. 

You can do finite difference modeling with “sufdmod2”

**Comment by LeeyMessi** [comment]
Thank your attention! I am reading your `A Course in Geophysical Image Processing with Seismic Unix:GPGN 461/561 Lab Fall 2012` , I want to add multiples to *.su file like the examples provided on page 142 of your document.

**Comment by LeeyMessi** [comment]
Hello, Sir! I make a stupid error because of my careless, but I have made a change. When I practiced according to the operation manual, there was another problem--`MakeFake: command not found` after running `MakeFake`. I swear I have copied this script to the current directory.

**Comment by JohnWStockwellJr** [comment]
The scripts are all in $CWPROOT/src/doc/GPGN461.561

Try typing 
./MakeFake

Make sure “.” Is in your path.

**Comment by JohnWStockwellJr** [comment]
Please contact me directly at john.19071969@gmail.com <mailto:john.19071969@gmail.com>  so I can send you Dropbox links to
more recent versions of the items you are working with.

**Comment by LeeyMessi** [comment]
Very nice! I have solved the problem with your help. I have sent my Gmail to you, please check your email.
