### ISSUE TITLE
Error when compiling fortran code under Ubuntu 18 LTS

### ISSUE THREAD

**Issue by nkeito** [JohnWStockwellJr/SeisUnix#20]
I'm facing a weird error when using Ubuntu 18 LTS (64 bits) when compiling with

`make finstall`

The particular error comes in the vzest folder

`make[2]: Entering directory '/home/angel/SeismicRoot/SeisUnix-master/src/Fortran/Vzest'
gfortran ./vzestf.o ./vzestsubf.o ./vzestc.o  -o /home/angel/SeismicRoot/SeisUnix-master/bin/vzest -lm  
/usr/bin/ld: ./vzestf.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ./vzestsubf.o: relocation R_X86_64_32S against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:17: /home/angel/SeismicRoot/SeisUnix-master/bin/vzest] Error 1
make[2]: Leaving directory '/home/angel/SeismicRoot/SeisUnix-master/src/Fortran/Vzest'
make[1]: *** [Makefile:14: INSTALL] Error 2
make[1]: Leaving directory '/home/angel/SeismicRoot/SeisUnix-master/src/Fortran'
make: *** [Makefile:126: finstall] Error 2
`

It's a weird error beacause the other installers work fine and also I'm able to install SU under Ubuntu 16 LTS (64 bits) without any error.

Edit:
Thanks for the answer

**Comment by JohnWStockwellJr** [comment]
The FORTRAN codes are always trouble. You can safely ignore it. It is unlikely you will use that code.
