### ISSUE TITLE
Installing on MacOS Mojave 

### ISSUE THREAD

**Issue by btozer** [JohnWStockwellJr/SeisUnix#23]
A note for anyone else who may have problems compiling on macOS Mojave.

I followed the first couple of instructions (as listed in the link below) to install the required system headers in the old locations:

https://solarianprogrammer.com/2017/05/21/compiling-gcc-macos/

It may be worth adding this step to the MacOS installation instructions on the wiki.

**Comment by JohnWStockwellJr** [comment]
Install MacPorts and install gcc from there.
