### ISSUE TITLE
Can't use segdread

### ISSUE THREAD

**Issue by guchchcug** [JohnWStockwellJr/SeisUnix#25]
Hi, 

I have some SEG D files to read, but the "segdread" doesn't work. It shows that "cannot execute binary file". Other SU tools work well. Thank you!

Chen

**Comment by guchchcug** [comment]
Solved. segdread needs to be reinstalled in the folder ~/src/Sfio

**Comment by JohnWStockwellJr** [comment]
Have you done the: make sfremake   ?
It’s a problem code

**Comment by guchchcug** [comment]
Hi John,

Thank you very much for the quick reply! I’ve fixed the problem and closed the issue by recompiling “segdread” in the folder Sfio/.

Chen

----------------------------------------------------
Chen Gu, Ph.D.
Postdoctoral Associate
Earth Resources Laboratory
Department of Earth, Atmospheric and Planetary Sciences
Massachusetts Institute of Technology
77 Mass Ave., 54-617
Cambridge, MA 02139
Telephone: 617-253-7278
Cell: 617-416-6058
Email: guchch@mit.edu<mailto:guchch@mit.edu>
Website: http://www.chenguatmit.com

On Mar 5, 2019, at 6:21 PM, John Stockwell <notifications@github.com<mailto:notifications@github.com>> wrote:

Have you done the: make sfremake ?
It’s a problem code
