### ISSUE TITLE
Where are the other files on the mines ftp?

### ISSUE THREAD

**Issue by Dev-Nebe** [JohnWStockwellJr/SeisUnix#26]
I'm trying to access the other files which were on the ftp server where SU was formerly hosted. Do you have any idea where these files are currently located?

(I'm specifically trying to access **ftp://ftp.cwp.mines.edu/pub/data/oz.original/README**)

Thanks.

**Comment by JohnWStockwellJr** [comment]
All that stuff was taken down when I retired. I can send you a DropBox link if you send me your email address.
I can’t do that through this medium.  You can send me direct email at:    John.19071969@gmail.com

**Comment by Dev-Nebe** [comment]
Oh thank you. I've gotten the link you sent to my email and it worked. I noticed you sent just the oz_original folder though. Is it possible that I get access to the whole /data folder? or any of the other folders (besides /oz_original) which you think contain all the resources I might need.

I'm asking because I'm currently learning seismic processing using  the **Seismic Data Processing with Seismic Unix** book and I don't want to bother you in the future if I need anything else from the dropbox folder while studying.

If you think the oz_original folder is sufficient then just let me know.

Thank you.
