### ISSUE TITLE
ar: libcwell.a: Malformed archive

### ISSUE THREAD

**Issue by SteveGitHubCable** [JohnWStockwellJr/SeisUnix#32]
When I run make finstall, it fails, saying:
make[2]: Warning: Archive 'libcwell.a' seems to have been created in deterministic mode. 'shoot.o' will always be updated. Please consider passing the U flag to ar to avoid the problem.
gfortran -g  -ffixed-line-length-none  -c -o shoot.o shoot.f
ar rv libcwell.a shoot.o
ar: libcwell.a: Malformed archive

I can follow those instructions to pass the U flag, by editing the Makefile.config file to set:
    ARFLAGS = rvU
When I do that, it still reports the same warning, and says:
ar rvU libcwell.a shoot.o
ar: libcwell.a: Malformed archive

I am running Ubunto 18.04, code name bionic.

I notice this file, libcwell.a is supplied in the GitHub down load from $CWPROOT/src/Fortran/Cwell/libcwell.a, recently updated 'last month', with the comment 'Updated sugain.c'

Can I do anything to re-form this archive?

**Comment by JohnWStockwellJr** [comment]
Try: make fremake

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by JohnWStockwellJr** [comment]
Please download the latest distribution files from: 
https://wiki.Seismic-Unix.org

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
