### ISSUE TITLE
Failed make install (openSUSE )

### ISSUE THREAD

**Issue by felikssartorius** [JohnWStockwellJr/SeisUnix#35]
Hello,

my issue seems similar to #12 but I am not capable of figuring out what is the problem based on solutions presented in that issue.

I receive similar errors after executing make install command, however libtirpc and libtirpc-devel are already installed at my machine. 

My /usr/include/ folder does not include tirpc folder, only rpc. So I have created a symbolic link: `ln -s /usr/include/rpc/* /usr/include/tirpc/`.
This hasn't changed to result.

I have installed all packages listed as prerequisites on the github page "Seismic Unix install on Linux".

My system is: openSUSE Tumbleweed
SU: 44R16 (downloaded from SU wiki page)

I use default Makefile.config file (I tried replacing it with Makefile.config_Linux_x86_64 but the result stays the same).

Thank  you for your help!
Kind regards,
Feliks Sartorius

Error message after executing make install:
`
cd amplitudes ; make
make[3]: Entering directory '/usr/local/cwp/src/su/main/amplitudes'
gcc -I/usr/local/cwp/include -O  -std=c99 -Wall -pedantic -Wno-long-long  -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DCWP_LITTLE_ENDIAN -DSUXDR  -D_BSD_SOURCE -D_POSIX_SOURCE sucentsamp.c  -L/usr/local/cwp/lib -lsu -lpar -lcwp -lm  -o /usr/local/cwp/bin/sucentsamp
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from /usr/local/cwp/include/cwp.h:12,
                 from /usr/local/cwp/include/par.h:12,
                 from /usr/local/cwp/include/su.h:14,
                 from sucentsamp.c:4:
/usr/include/features.h:185:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  185 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
 |   
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(fgettr.o): in function `dataread':
fgettr.c:(.text+0x173): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: fgettr.c:(.text+0x180): undefined reference to `xdr_vector'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(fgettr.o): in function `fgettr_internal':
fgettr.c:(.text+0x2d9): undefined reference to `xdrmem_create'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(fputtr.o): in function `fputtr_internal':
fputtr.c:(.text+0x12e): undefined reference to `xdrmem_create'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: fputtr.c:(.text+0x233): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: fputtr.c:(.text+0x23d): undefined reference to `xdr_vector'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o): in function `xdrhdrsub':
xdrhdrsub.c:(.text+0x16): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x38): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x4b): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x5e): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x71): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o):xdrhdrsub.c:(.text+0x84): more undefined references to `xdr_int' follow
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o): in function `xdrhdrsub':
xdrhdrsub.c:(.text+0xcb): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0xed): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x110): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x130): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x161): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x178): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x18f): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x1a6): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x1bd): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o):xdrhdrsub.c:(.text+0x1d4): more undefined references to `xdr_int' follow
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o): in function `xdrhdrsub':
xdrhdrsub.c:(.text+0x237): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x24a): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x261): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x278): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x28f): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x2c4): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x2ec): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x314): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x33c): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x364): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o):xdrhdrsub.c:(.text+0x38c): more undefined references to `xdr_u_int' follow
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o): in function `xdrhdrsub':
xdrhdrsub.c:(.text+0x698): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x6b2): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x6cc): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x6e6): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x700): undefined reference to `xdr_float'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o):xdrhdrsub.c:(.text+0x71a): more undefined references to `xdr_float' follow
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o): in function `xdrhdrsub':
xdrhdrsub.c:(.text+0x734): undefined reference to `xdr_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x76f): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x79f): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x7cc): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x7f9): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: xdrhdrsub.c:(.text+0x826): undefined reference to `xdr_u_int'
/usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /usr/local/cwp/lib/libsu.a(xdrhdrsub.o):xdrhdrsub.c:(.text+0x853): more undefined references to `xdr_u_int' follow
collect2: error: ld returned 1 exit status
make[3]: [Makefile:31: /usr/local/cwp/bin/sucentsamp] Error 1 (ignored)
chmod: cannot access '/usr/local/cwp/bin/sucentsamp': No such file or directory
make[3]: *** [Makefile:32: /usr/local/cwp/bin/sucentsamp] Error 1
make[3]: Leaving directory '/usr/local/cwp/src/su/main/amplitudes'
make[2]: *** [Makefile:6: INSTALL] Error 2
make[2]: Leaving directory '/usr/local/cwp/src/su/main'
make[1]: *** [Makefile:8: INSTALL] Error 2
make[1]: Leaving directory '/usr/local/cwp/src/su'
make: *** [Makefile:92: sustuff] Error 2
`

**Comment by JohnWStockwellJr** [comment]
You need to install the rpc libraries it will look like librpc-dev or something and

You will then  need to add -ltirpc
To the OPTC 
line in Makefile.config

Never make modifications to system level directories, except by using the package manager.


John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by felikssartorius** [comment]
Thank you very much for the help.
It worked.

**Comment by JohnWStockwellJr** [comment]
You can also modify the Makefile.config to silence the complaints about  deprecated flags.
Make that change, and then to

   make remake
   make xtremake
   etc.

After you get that working, please send me the modified Makefile.config so I can include it in the distribution.
