### ISSUE TITLE
Cannot build source code in OSX

### ISSUE THREAD

**Issue by brainstormot** [JohnWStockwellJr/SeisUnix#4]
Hello

I got some trouble with install seismic unix on my macbook. OS is OSX Sierra. I set environment varibles for installing and tried to 'make install' but I got an error below.

![image](https://cloud.githubusercontent.com/assets/9497946/23262979/09909e42-fa20-11e6-9a2b-1640e9a6d12c.png)

and 'make xtinstall' also invoked another error

<img width="1280" alt="image" src="https://cloud.githubusercontent.com/assets/9497946/23263095/78ec682a-fa20-11e6-9329-21d5842139b2.png">

I don't know how to deal with this errors.

Is there anything which I missed?

**Comment by JohnWStockwellJr** [comment]
Hi,
First make sure that you have copied
the Makefile.config for the latest version of Mac OS X from $CWPROOT/src/configs
To
$CWPROOT/arc/Makefile.config

You need to install the most current version of XCode from the AppStore.
You will also need to install XQuartz for the X-windows graphics, and you might want to install MacPorts.

The only parts of the installation you need are
cd $CWPROOT/src 
make install      (Or make remake)
make xtinstall    (Or make xtremake)

-John

**Comment by brainstormot** [comment]
Thanks for your fast reply

The above problem is clearly solved by installing Xquartz.

But another error appeared like below. (with "make install")
 
<img width="1278" alt="image" src="https://cloud.githubusercontent.com/assets/9497946/23285549/3e71cb40-fa75-11e6-98d6-00ba1a575319.png">

It only happend when I use 'icc' but doesn't happed when I use 'gcc'

It is caused by comment grammer "//". if "//" comment is replaeced by "/* */", then the error is solved. As I know, "//" is not standard commment in c, but standard in c++". In c, "//" comment grammer haved been includend since c99.

But default complie option in seismic unix is "-std=c90".

So I think it is better to change "-std=c90" to "-std=c99" or change "//" to "/* */".

I think the latter is better

**Comment by JohnWStockwellJr** [comment]
I got rid of the //     I was not aware that those were in there. Thanks.
