### ISSUE TITLE
SU Manual Link Not Working

### ISSUE THREAD

**Issue by nate-benton90** [JohnWStockwellJr/SeisUnix#47]
Upon clicking the PDF link [ftp://ftp.cwp.mines.edu/pub/cwpcodes/sumanual_300dpi_a4.pdf] for viewing, no response follows.

**Comment by JohnWStockwellJr** [comment]
The official site of SU is the address below my signature.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
