### ISSUE TITLE
WGET for Download Fails & CWP Link Not Working

### ISSUE THREAD

**Issue by nate-benton90** [JohnWStockwellJr/SeisUnix#48]
**1**) According to Linux download notes [here](https://github.com/JohnWStockwellJr/SeisUnix/wiki/Seismic-Unix-install-on-Linux), the WGET command fails as indicated by image showing the log output. What may be causing this?

_IMAGE 1_
<img width="1046" alt="Screen Shot 2019-11-16 at 12 32 47 PM" src="https://user-images.githubusercontent.com/44947087/68997653-60b32780-086e-11ea-9a51-8dbdc3e85451.png">

**2**) The CWP link is also unresponsive.
*Note I am running an Linux EC2 instance with the following specifications as indicated by the following two images below:

_IMAGE 2_
<img width="1198" alt="Screen Shot 2019-11-16 at 12 34 39 PM" src="https://user-images.githubusercontent.com/44947087/68997710-f0f16c80-086e-11ea-888b-30fc337174e2.png">

_IMAGE 3_
<img width="813" alt="Screen Shot 2019-11-16 at 12 34 14 PM" src="https://user-images.githubusercontent.com/44947087/68997714-f9e23e00-086e-11ea-8edb-f460fbefade2.png">

**Comment by JohnWStockwellJr** [comment]
Yes. SU isn’t at Mines anymore. I retired 2 years ago. The new site it: https://wiki.Seismic-Unix.org

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by nate-benton90** [comment]
Thank you for building and supplying that, Dr. Stockwell. I have now closed the issue.

**Comment by AmenBargees** [comment]
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
