### ISSUE TITLE
Error while sorting CDP

### ISSUE THREAD

**Issue by tgautam03** [JohnWStockwellJr/SeisUnix#50]
I am trying to sort traces by CDP and I am getting the following error
`surange: fgettr.c: on trace #1, number of samples in header (20662) differs from number for first trace (62721)`

My code is 
`/bin/sh` 
`suchw<seis4.su key1=cdp key2=gx key3=sx \`		
`a=1525 b=1 c=1 d=50 |susort>cmp4.su cdp offset`
`exit 0`

**Comment by JohnWStockwellJr** [comment]
You can’t sort from a pipe or to a pipe, only from file to file

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by tgautam03** [comment]
Thanks...
