### ISSUE TITLE
suztot issues?

### ISSUE THREAD

**Issue by mithcell** [JohnWStockwellJr/SeisUnix#64]
Anyone had luck using this module successfully? I get a result with the correct sample rate but the stretching hasn't worked. Perhaps the interpolation has a bug....

**Comment by JohnWStockwellJr** [comment]
The program works just fine. It is for stretching data in depth to time. It is the inverse of “suttoz”

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by mithcell** [comment]
Thank you for the reply.

I find that I can convert a v(z) model to v(t) using:
velconv intype=vintz outtype=vintt nz=300 dz=10 dt=0.004 nt=1001 <marmousi.bin | suaddhead ns=1001 | suximage

Now that I know what this model will look like in time, I try to use suztot but can't acheive the desired result:
suztot vfile=marmousi.bin <marmousi.su nt=1001 dt=0.004 verbose=1 | suaddhead ns=1001 | suximage

suztot: Input:
suztot: 	number of depth samples = 300
suztot: 	depth sampling interval = 10
suztot: 	first depth sample = 0

suztot: Output:
suztot: 	number of time samples = 1001
suztot: 	time sampling interval = 0.004
suztot: 	first time sample = 0

Any suggestions?

Thank you

**Comment by JohnWStockwellJr** [comment]
When it says v(t) or v(z) it means that the velocity profile is one dimensional. 
While it is possible, with care, to use velconv to convert a v(z,x) file to a v(t,x), and vice versa, the programs suttoz and suztot do not support v(t,x) or v(z,x) files. These support only v(t) or v(z) velocity profiles.

For your Marmousi profiles, the best you could do would be to use suaddhead to put su headers on the Marmousi models and use sustack to average the models to create average v(z) and v(t) files. These could then be used with suttoz and suztot.

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x
