### ISSUE TITLE
Error on make install

### ISSUE THREAD

**Issue by malapradej** [JohnWStockwellJr/SeisUnix#73]
I am trying to install SU in a centos 7 server. I get the following error when running 
`make install`

/usr/bin/gcc -c -I/home/jmalaprade/source/SeisUnix/include -g -std=c90  -m64 -Wall -ansi  -Wno-long-long   -DCWP_LITTLE_ENDIAN -DSUXDR  getSPSfield.c
getSPSfield.c:45:1: error: expected identifier or ‘(’ before ‘/’ token
 //  Version 0 record description:
 ^
getSPSfield.c:61:59: error: invalid suffix "I2" on integer constant
       { 74, 6, "%d","Time"     },  // 14 Time of day     (2I2 in std)
                                                           ^
getSPSfield.c:66:36: error: expected expression before ‘/’ token
       {  0, 1, "%c","RecTyp"   },  //  0 Label X
                                    ^
getSPSfield.c:84:1: error: expected identifier or ‘(’ before ‘/’ token
 //  Version 2.1 record description:
 ^
getSPSfield.c:100:59: error: invalid suffix "I2" on integer constant
       { 74, 6, "%d","Time"     }   // 14 Time of day     (3I2 in std)
                                                           ^
getSPSfield.c:105:35: error: expected expression before ‘/’ token
       {  0, 1, "%c","RecTyp"   }, //  0 Label X
                                   ^
getSPSfield.c:105:35: warning: missing braces around initializer [-Wmissing-braces]
getSPSfield.c:105:35: warning: (near initialization for ‘xparse2[1]’) [-Wmissing-braces]
getSPSfield.c:105:35: error: initializer element is not constant
getSPSfield.c:105:35: error: (near initialization for ‘xparse2[1].st’)
getSPSfield.c: In function ‘getSPSfield’:
getSPSfield.c:130:10: error: expected expression before ‘/’ token
          // throw a tantrum
          ^
getSPSfield.c:130:10: warning: statement with no effect [-Wunused-value]
getSPSfield.c:137:19: error: ‘pparse0’ undeclared (first use in this function)
          pparse = pparse0;
                   ^
getSPSfield.c:137:19: note: each undeclared identifier is reported only once for each function it appears in
getSPSfield.c:139:19: error: ‘pparse2’ undeclared (first use in this function)
          pparse = pparse2;
                   ^
getSPSfield.c:166:4: error: expected expression before ‘/’ token
    // Save the starting character of next field
    ^
getSPSfield.c:166:4: warning: statement with no effect [-Wunused-value]
make[2]: *** [/home/jmalaprade/source/SeisUnix/lib/libsu.a(getSPSfield.o)] Error 1
make[2]: Leaving directory `/home/jmalaprade/source/SeisUnix/src/su/lib'
make[1]: *** [INSTALL] Error 2
make[1]: Leaving directory `/home/jmalaprade/source/SeisUnix/src/su'
make: *** [sustuff] Error 2

**Comment by JohnWStockwellJr** [comment]
Please download the current version of src/su/lib/getSPSfield.c   from the GitHub site and replace your version
With that version. Let me know if that works. 

Or you can go through and  look for all of the comments that start with
// comments 

And put these in the  form of
/*  comments */

And then try doing 
   make remake

**Comment by malapradej** [comment]
Thanks a lot. Before I saw your message I downloaded the latest version and it installed without a problem using the default Makefile.config.
