### ISSUE TITLE
Install issue with command "make xinstall"

### ISSUE THREAD

**Issue by illusion899** [JohnWStockwellJr/SeisUnix#78]
Hi, 

I'm trying to install the package ion the virtual CentOS 7 in based on VMare Fusion on a Macbook. The config file i used was Makefile.config_Linux_x86_64 and it worked great until i was trying to run `make xtinstall `. Then the feedback i got is 

>  make: *** No rule to make target `xinstall'.  Stop.
 
It will be great if I can get some guidance on how to proceed. 

Thanks in advance~

**Comment by JohnWStockwellJr** [comment]
I suspect you may have typed: make xinstall 
Instead of: make xtinstall

John Stockwell
Visit: https://wiki.Seismic-Unix.org
The new home of Seismic Un*x

**Comment by illusion899** [comment]
You are absolutely right Sir. I'm so embarrassed that I opened this issue.... 
Thank you so much for the timely reply, I really appreciate the help. 
Have a great night, and I will close the issue with shame....
